<?php

namespace Database\Seeders;

use App\Models\WeekDayAvailable;
use Illuminate\Database\Seeder;

class WeekDayAvailableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user1 = new WeekDayAvailable;
        $user1->id = "1";
        $user1->provider_id = "1";
        $user1->week_id = "1";
        $user1->weekday_id = "1";
        $user1->day_start_time = "10:00:00";
        $user1->day_end_time = "20:00:00";
        $user1->off_day = "N";
        $user1->provider_schedule_type = "Weekly";
        $user1->created_by = "1";
        $user1->updated_by = "1";
        $user1->save();
        
        $user2 = new WeekDayAvailable;
        $user2->id = "2";
        $user2->provider_id = "1";
        $user2->week_id = "1";
        $user2->weekday_id = "2";
        $user2->day_start_time = "10:00:00";
        $user2->day_end_time = "20:00:00";
        $user2->off_day = "N";
        $user2->provider_schedule_type = "Weekly";
        $user2->created_by = "2";
        $user2->updated_by = "2";
        $user2->save();

        $user3 = new WeekDayAvailable;
        $user3->id = "3";
        $user3->provider_id = "1";
        $user3->week_id = "1";
        $user3->weekday_id = "3";
        $user3->day_start_time = "10:00:00";
        $user3->day_end_time = "20:00:00";
        $user3->off_day = "N";
        $user3->provider_schedule_type = "Weekly";
        $user3->created_by = "3";
        $user3->updated_by = "3";
        $user3->save();

        $user4 = new WeekDayAvailable;
        $user4->id = "4";
        $user4->provider_id = "1";
        $user4->week_id = "1";
        $user4->weekday_id = "4";
        $user4->day_start_time = "10:00:00";
        $user4->day_end_time = "20:00:00";
        $user4->off_day = "N";
        $user4->provider_schedule_type = "Weekly";
        $user4->created_by = "4";
        $user4->updated_by = "4";
        $user4->save();

        $user5 = new WeekDayAvailable;
        $user5->id = "5";
        $user5->provider_id = "1";
        $user5->week_id = "1";
        $user5->weekday_id = "5";
        $user5->day_start_time = "10:00:00";
        $user5->day_end_time = "20:00:00";
        $user5->off_day = "N";
        $user5->provider_schedule_type = "Weekly";
        $user5->created_by = "5";
        $user5->updated_by = "5";
        $user5->save();

        $user6 = new WeekDayAvailable;
        $user6->id = "6";
        $user6->provider_id = "1";
        $user6->week_id = "1";
        $user6->weekday_id = "6";
        $user6->day_start_time = "10:00:00";
        $user6->day_end_time = "20:00:00";
        $user6->off_day = "N";
        $user6->provider_schedule_type = "Weekly";
        $user6->created_by = "6";
        $user6->updated_by = "6";
        $user6->save();

        $user7 = new WeekDayAvailable;
        $user7->id = "7";
        $user7->provider_id = "1";
        $user7->week_id = "1";
        $user7->weekday_id = "7";
        $user7->day_start_time = "10:00:00";
        $user7->day_end_time = "20:00:00";
        $user7->off_day = "Y";
        $user7->provider_schedule_type = "Weekly";
        $user7->created_by = "7";
        $user7->updated_by = "7";
        $user7->save();

        $user8 = new WeekDayAvailable;
        $user8->id = "8";
        $user8->provider_id = "2";
        $user8->week_id = "1";
        $user8->weekday_id = "1";
        $user8->day_start_time = "08:00:00";
        $user8->day_end_time = "17:00:00";
        $user8->off_day = "N";
        $user8->provider_schedule_type = "Weekly";
        $user8->created_by = "8";
        $user8->updated_by = "8";
        $user8->save();

        $user9 = new WeekDayAvailable;
        $user9->id = "9";
        $user9->provider_id = "2";
        $user9->week_id = "1";
        $user9->weekday_id = "2";
        $user9->day_start_time = "08:00:00";
        $user9->day_end_time = "17:00:00";
        $user9->off_day = "N";
        $user9->provider_schedule_type = "Weekly";
        $user9->created_by = "9";
        $user9->updated_by = "9";
        $user9->save();

        $user10 = new WeekDayAvailable;
        $user10->id = "10";
        $user10->provider_id = "2";
        $user10->week_id = "1";
        $user10->weekday_id = "3";
        $user10->day_start_time = "08:00:00";
        $user10->day_end_time = "17:00:00";
        $user10->off_day = "N";
        $user10->provider_schedule_type = "Weekly";
        $user10->created_by = "10";
        $user10->updated_by = "10";
        $user10->save();

        $user11 = new WeekDayAvailable;
        $user11->id = "11";
        $user11->provider_id = "2";
        $user11->week_id = "1";
        $user11->weekday_id = "4";
        $user11->day_start_time = "08:00:00";
        $user11->day_end_time = "17:00:00";
        $user11->off_day = "N";
        $user11->provider_schedule_type = "Weekly";
        $user11->created_by = "11";
        $user11->updated_by = "11";
        $user11->save();

        $user12 = new WeekDayAvailable;
        $user12->id = "12";
        $user12->provider_id = "2";
        $user12->week_id = "1";
        $user12->weekday_id = "5";
        $user12->day_start_time = "08:00:00";
        $user12->day_end_time = "17:00:00";
        $user12->off_day = "N";
        $user12->provider_schedule_type = "Weekly";
        $user12->created_by = "12";
        $user12->updated_by = "12";
        $user12->save();

        $user13 = new WeekDayAvailable;
        $user13->id = "13";
        $user13->provider_id = "2";
        $user13->week_id = "1";
        $user13->weekday_id = "6";
        $user13->day_start_time = "08:00:00";
        $user13->day_end_time = "17:00:00";
        $user13->off_day = "N";
        $user13->provider_schedule_type = "Weekly";
        $user13->created_by = "13";
        $user13->updated_by = "13";
        $user13->save();

        $user14 = new WeekDayAvailable;
        $user14->id = "14";
        $user14->provider_id = "2";
        $user14->week_id = "1";
        $user14->weekday_id = "7";
        $user14->day_start_time = "08:00:00";
        $user14->day_end_time = "17:00:00";
        $user14->off_day = "N";
        $user14->provider_schedule_type = "Weekly";
        $user14->created_by = "14";
        $user14->updated_by = "14";
        $user14->save();

        $user15 = new WeekDayAvailable;
        $user15->id = "15";
        $user15->provider_id = "3";
        $user15->week_id = "1";
        $user15->weekday_id = "1";
        $user15->day_start_time = "08:00:00";
        $user15->day_end_time = "17:00:00";
        $user15->off_day = "N";
        $user15->provider_schedule_type = "Weekly";
        $user15->created_by = "15";
        $user15->updated_by = "15";
        $user15->save();

        $user16 = new WeekDayAvailable;
        $user16->id = "16";
        $user16->provider_id = "3";
        $user16->week_id = "1";
        $user16->weekday_id = "2";
        $user16->day_start_time = "08:00:00";
        $user16->day_end_time = "17:00:00";
        $user16->off_day = "N";
        $user16->provider_schedule_type = "Weekly";
        $user16->created_by = "16";
        $user16->updated_by = "16";
        $user16->save();

        $user17 = new WeekDayAvailable;
        $user17->id = "17";
        $user17->provider_id = "3";
        $user17->week_id = "1";
        $user17->weekday_id = "3";
        $user17->day_start_time = "08:00:00";
        $user17->day_end_time = "17:00:00";
        $user17->off_day = "N";
        $user17->provider_schedule_type = "Weekly";
        $user17->created_by = "17";
        $user17->updated_by = "17";
        $user17->save();

        $user18 = new WeekDayAvailable;
        $user18->id = "18";
        $user18->provider_id = "3";
        $user18->week_id = "1";
        $user18->weekday_id = "4";
        $user18->day_start_time = "08:00:00";
        $user18->day_end_time = "17:00:00";
        $user18->off_day = "N";
        $user18->provider_schedule_type = "Weekly";
        $user18->created_by = "18";
        $user18->updated_by = "18";
        $user18->save();

        $user19 = new WeekDayAvailable;
        $user19->id = "19";
        $user19->provider_id = "3";
        $user19->week_id = "1";
        $user19->weekday_id = "5";
        $user19->day_start_time = "08:00:00";
        $user19->day_end_time = "17:00:00";
        $user19->off_day = "N";
        $user19->provider_schedule_type = "Weekly";
        $user19->created_by = "19";
        $user19->updated_by = "19";
        $user19->save();

        $user20 = new WeekDayAvailable;
        $user20->id = "20";
        $user20->provider_id = "3";
        $user20->week_id = "1";
        $user20->weekday_id = "6";
        $user20->day_start_time = "08:00:00";
        $user20->day_end_time = "17:00:00";
        $user20->off_day = "N";
        $user20->provider_schedule_type = "Weekly";
        $user20->created_by = "20";
        $user20->updated_by = "20";
        $user20->save();

        $user21 = new WeekDayAvailable;
        $user21->id = "21";
        $user21->provider_id = "3";
        $user21->week_id = "1";
        $user21->weekday_id = "7";
        $user21->day_start_time = "08:00:00";
        $user21->day_end_time = "17:00:00";
        $user21->off_day = "N";
        $user21->provider_schedule_type = "Weekly";
        $user21->created_by = "21";
        $user21->updated_by = "21";
        $user21->save();

        $user29 = new WeekDayAvailable;
        $user29->id = "29";
        $user29->provider_id = "4";
        $user29->week_id = "1";
        $user29->weekday_id = "1";
        $user29->day_start_time = "08:00:00";
        $user29->day_end_time = "17:00:00";
        $user29->off_day = "N";
        $user29->provider_schedule_type = "Monthly";
        $user29->created_by = "29";
        $user29->updated_by = "29";
        $user29->save();

        $user30 = new WeekDayAvailable;
        $user30->id = "30";
        $user30->provider_id = "4";
        $user30->week_id = "1";
        $user30->weekday_id = "2";
        $user30->day_start_time = "08:00:00";
        $user30->day_end_time = "17:00:00";
        $user30->off_day = "N";
        $user30->provider_schedule_type = "Monthly";
        $user30->created_by = "30";
        $user30->updated_by = "30";
        $user30->save();

        $user31 = new WeekDayAvailable;
        $user31->id = "31";
        $user31->provider_id = "4";
        $user31->week_id = "1";
        $user31->weekday_id = "3";
        $user31->day_start_time = "08:00:00";
        $user31->day_end_time = "17:00:00";
        $user31->off_day = "N";
        $user31->provider_schedule_type = "Monthly";
        $user31->created_by = "31";
        $user31->updated_by = "31";
        $user31->save();

        $user32 = new WeekDayAvailable;
        $user32->id = "32";
        $user32->provider_id = "4";
        $user32->week_id = "1";
        $user32->weekday_id = "4";
        $user32->day_start_time = "08:00:00";
        $user32->day_end_time = "17:00:00";
        $user32->off_day = "N";
        $user32->provider_schedule_type = "Monthly";
        $user32->created_by = "32";
        $user32->updated_by = "32";
        $user32->save();

        $user33 = new WeekDayAvailable;
        $user33->id = "33";
        $user33->provider_id = "4";
        $user33->week_id = "1";
        $user33->weekday_id = "5";
        $user33->day_start_time = "08:00:00";
        $user33->day_end_time = "17:00:00";
        $user33->off_day = "N";
        $user33->provider_schedule_type = "Monthly";
        $user33->created_by = "33";
        $user33->updated_by = "33";
        $user33->save();

        $user34 = new WeekDayAvailable;
        $user34->id = "34";
        $user34->provider_id = "4";
        $user34->week_id = "1";
        $user34->weekday_id = "6";
        $user34->day_start_time = "08:00:00";
        $user34->day_end_time = "17:00:00";
        $user34->off_day = "N";
        $user34->provider_schedule_type = "Monthly";
        $user34->created_by = "34";
        $user34->updated_by = "34";
        $user34->save();

        $user35 = new WeekDayAvailable;
        $user35->id = "35";
        $user35->provider_id = "4";
        $user35->week_id = "1";
        $user35->weekday_id = "7";
        $user35->day_start_time = "08:00:00";
        $user35->day_end_time = "17:00:00";
        $user35->off_day = "N";
        $user35->provider_schedule_type = "Monthly";
        $user35->created_by = "35";
        $user35->updated_by = "35";
        $user35->save();

        $user36 = new WeekDayAvailable;
        $user36->id = "36";
        $user36->provider_id = "4";
        $user36->week_id = "2";
        $user36->weekday_id = "1";
        $user36->day_start_time = "08:00:00";
        $user36->day_end_time = "17:00:00";
        $user36->off_day = "N";
        $user36->provider_schedule_type = "Monthly";
        $user36->created_by = "36";
        $user36->updated_by = "36";
        $user36->save();

        $user37 = new WeekDayAvailable;
        $user37->id = "37";
        $user37->provider_id = "4";
        $user37->week_id = "2";
        $user37->weekday_id = "2";
        $user37->day_start_time = "08:00:00";
        $user37->day_end_time = "17:00:00";
        $user37->off_day = "N";
        $user37->provider_schedule_type = "Monthly";
        $user37->created_by = "37";
        $user37->updated_by = "37";
        $user37->save();

        $user38 = new WeekDayAvailable;
        $user38->id = "38";
        $user38->provider_id = "4";
        $user38->week_id = "2";
        $user38->weekday_id = "3";
        $user38->day_start_time = "08:00:00";
        $user38->day_end_time = "17:00:00";
        $user38->off_day = "N";
        $user38->provider_schedule_type = "Monthly";
        $user38->created_by = "38";
        $user38->updated_by = "38";
        $user38->save();

        $user39 = new WeekDayAvailable;
        $user39->id = "39";
        $user39->provider_id = "4";
        $user39->week_id = "2";
        $user39->weekday_id = "4";
        $user39->day_start_time = "08:00:00";
        $user39->day_end_time = "17:00:00";
        $user39->off_day = "N";
        $user39->provider_schedule_type = "Monthly";
        $user39->created_by = "39";
        $user39->updated_by = "39";
        $user39->save();

        $user40 = new WeekDayAvailable;
        $user40->id = "40";
        $user40->provider_id = "4";
        $user40->week_id = "2";
        $user40->weekday_id = "5";
        $user40->day_start_time = "08:00:00";
        $user40->day_end_time = "17:00:00";
        $user40->off_day = "N";
        $user40->provider_schedule_type = "Monthly";
        $user40->created_by = "40";
        $user40->updated_by = "40";
        $user40->save();

        $user41 = new WeekDayAvailable;
        $user41->id = "41";
        $user41->provider_id = "4";
        $user41->week_id = "2";
        $user41->weekday_id = "6";
        $user41->day_start_time = "08:00:00";
        $user41->day_end_time = "17:00:00";
        $user41->off_day = "N";
        $user41->provider_schedule_type = "Monthly";
        $user41->created_by = "41";
        $user41->updated_by = "41";
        $user41->save();

        $user42 = new WeekDayAvailable;
        $user42->id = "42";
        $user42->provider_id = "4";
        $user42->week_id = "2";
        $user42->weekday_id = "7";
        $user42->day_start_time = "08:00:00";
        $user42->day_end_time = "17:00:00";
        $user42->off_day = "N";
        $user42->provider_schedule_type = "Monthly";
        $user42->created_by = "42";
        $user42->updated_by = "42";
        $user42->save();

        $user43 = new WeekDayAvailable;
        $user43->id = "43";
        $user43->provider_id = "4";
        $user43->week_id = "3";
        $user43->weekday_id = "1";
        $user43->day_start_time = "08:00:00";
        $user43->day_end_time = "17:00:00";
        $user43->off_day = "N";
        $user43->provider_schedule_type = "Monthly";
        $user43->created_by = "43";
        $user43->updated_by = "43";
        $user43->save();

        $user44 = new WeekDayAvailable;
        $user44->id = "44";
        $user44->provider_id = "4";
        $user44->week_id = "3";
        $user44->weekday_id = "2";
        $user44->day_start_time = "08:00:00";
        $user44->day_end_time = "17:00:00";
        $user44->off_day = "N";
        $user44->provider_schedule_type = "Monthly";
        $user44->created_by = "44";
        $user44->updated_by = "44";
        $user44->save();

        $user45 = new WeekDayAvailable;
        $user45->id = "45";
        $user45->provider_id = "4";
        $user45->week_id = "3";
        $user45->weekday_id = "3";
        $user45->day_start_time = "08:00:00";
        $user45->day_end_time = "17:00:00";
        $user45->off_day = "N";
        $user45->provider_schedule_type = "Monthly";
        $user45->created_by = "45";
        $user45->updated_by = "45";
        $user45->save();

        $user46 = new WeekDayAvailable;
        $user46->id = "46";
        $user46->provider_id = "4";
        $user46->week_id = "3";
        $user46->weekday_id = "4";
        $user46->day_start_time = "08:00:00";
        $user46->day_end_time = "17:00:00";
        $user46->off_day = "N";
        $user46->provider_schedule_type = "Monthly";
        $user46->created_by = "46";
        $user46->updated_by = "46";
        $user46->save();

        $user47 = new WeekDayAvailable;
        $user47->id = "47";
        $user47->provider_id = "4";
        $user47->week_id = "3";
        $user47->weekday_id = "5";
        $user47->day_start_time = "08:00:00";
        $user47->day_end_time = "17:00:00";
        $user47->off_day = "N";
        $user47->provider_schedule_type = "Monthly";
        $user47->created_by = "47";
        $user47->updated_by = "47";
        $user47->save();

        $user48 = new WeekDayAvailable;
        $user48->id = "48";
        $user48->provider_id = "4";
        $user48->week_id = "3";
        $user48->weekday_id = "6";
        $user48->day_start_time = "08:00:00";
        $user48->day_end_time = "17:00:00";
        $user48->off_day = "N";
        $user48->provider_schedule_type = "Monthly";
        $user48->created_by = "48";
        $user48->updated_by = "48";
        $user48->save();

        $user49 = new WeekDayAvailable;
        $user49->id = "49";
        $user49->provider_id = "4";
        $user49->week_id = "3";
        $user49->weekday_id = "7";
        $user49->day_start_time = "08:00:00";
        $user49->day_end_time = "17:00:00";
        $user49->off_day = "N";
        $user49->provider_schedule_type = "Monthly";
        $user49->created_by = "49";
        $user49->updated_by = "49";
        $user49->save();

        $user50 = new WeekDayAvailable;
        $user50->id = "50";
        $user50->provider_id = "4";
        $user50->week_id = "4";
        $user50->weekday_id = "1";
        $user50->day_start_time = "08:00:00";
        $user50->day_end_time = "17:00:00";
        $user50->off_day = "N";
        $user50->provider_schedule_type = "Monthly";
        $user50->created_by = "50";
        $user50->updated_by = "50";
        $user50->save();

        $user51 = new WeekDayAvailable;
        $user51->id = "51";
        $user51->provider_id = "4";
        $user51->week_id = "4";
        $user51->weekday_id = "2";
        $user51->day_start_time = "08:00:00";
        $user51->day_end_time = "17:00:00";
        $user51->off_day = "N";
        $user51->provider_schedule_type = "Monthly";
        $user51->created_by = "51";
        $user51->updated_by = "51";
        $user51->save();

        $user52 = new WeekDayAvailable;
        $user52->id = "52";
        $user52->provider_id = "4";
        $user52->week_id = "4";
        $user52->weekday_id = "3";
        $user52->day_start_time = "08:00:00";
        $user52->day_end_time = "17:00:00";
        $user52->off_day = "N";
        $user52->provider_schedule_type = "Monthly";
        $user52->created_by = "52";
        $user52->updated_by = "52";
        $user52->save();

        $user53 = new WeekDayAvailable;
        $user53->id = "53";
        $user53->provider_id = "4";
        $user53->week_id = "4";
        $user53->weekday_id = "4";
        $user53->day_start_time = "08:00:00";
        $user53->day_end_time = "17:00:00";
        $user53->off_day = "N";
        $user53->provider_schedule_type = "Monthly";
        $user53->created_by = "53";
        $user53->updated_by = "53";
        $user53->save();

        $user54 = new WeekDayAvailable;
        $user54->id = "54";
        $user54->provider_id = "4";
        $user54->week_id = "4";
        $user54->weekday_id = "5";
        $user54->day_start_time = "08:00:00";
        $user54->day_end_time = "17:00:00";
        $user54->off_day = "N";
        $user54->provider_schedule_type = "Monthly";
        $user54->created_by = "54";
        $user54->updated_by = "54";
        $user54->save();

        $user55 = new WeekDayAvailable;
        $user55->id = "55";
        $user55->provider_id = "4";
        $user55->week_id = "4";
        $user55->weekday_id = "6";
        $user55->day_start_time = "08:00:00";
        $user55->day_end_time = "17:00:00";
        $user55->off_day = "N";
        $user55->provider_schedule_type = "Monthly";
        $user55->created_by = "55";
        $user55->updated_by = "55";
        $user55->save();

        $user56 = new WeekDayAvailable;
        $user56->id = "56";
        $user56->provider_id = "4";
        $user56->week_id = "4";
        $user56->weekday_id = "7";
        $user56->day_start_time = "08:00:00";
        $user56->day_end_time = "17:00:00";
        $user56->off_day = "N";
        $user56->provider_schedule_type = "Monthly";
        $user56->created_by = "56";
        $user56->updated_by = "56";
        $user56->save();

        $user57 = new WeekDayAvailable;
        $user57->id = "57";
        $user57->provider_id = "4";
        $user57->week_id = "5";
        $user57->weekday_id = "1";
        $user57->day_start_time = "08:00:00";
        $user57->day_end_time = "17:00:00";
        $user57->off_day = "N";
        $user57->provider_schedule_type = "Monthly";
        $user57->created_by = "57";
        $user57->updated_by = "57";
        $user57->save();

        $user58 = new WeekDayAvailable;
        $user58->id = "58";
        $user58->provider_id = "4";
        $user58->week_id = "5";
        $user58->weekday_id = "2";
        $user58->day_start_time = "08:00:00";
        $user58->day_end_time = "17:00:00";
        $user58->off_day = "N";
        $user58->provider_schedule_type = "Monthly";
        $user58->created_by = "58";
        $user58->updated_by = "58";
        $user58->save();

        $user59 = new WeekDayAvailable;
        $user59->id = "59";
        $user59->provider_id = "4";
        $user59->week_id = "5";
        $user59->weekday_id = "3";
        $user59->day_start_time = "08:00:00";
        $user59->day_end_time = "17:00:00";
        $user59->off_day = "N";
        $user59->provider_schedule_type = "Monthly";
        $user59->created_by = "59";
        $user59->updated_by = "59";
        $user59->save();

        $user60 = new WeekDayAvailable;
        $user60->id = "60";
        $user60->provider_id = "4";
        $user60->week_id = "5";
        $user60->weekday_id = "4";
        $user60->day_start_time = "08:00:00";
        $user60->day_end_time = "17:00:00";
        $user60->off_day = "N";
        $user60->provider_schedule_type = "Monthly";
        $user60->created_by = "60";
        $user60->updated_by = "60";
        $user60->save();

        $user61 = new WeekDayAvailable;
        $user61->id = "61";
        $user61->provider_id = "4";
        $user61->week_id = "5";
        $user61->weekday_id = "5";
        $user61->day_start_time = "08:00:00";
        $user61->day_end_time = "17:00:00";
        $user61->off_day = "N";
        $user61->provider_schedule_type = "Monthly";
        $user61->created_by = "61";
        $user61->updated_by = "61";
        $user61->save();

        $user62 = new WeekDayAvailable;
        $user62->id = "62";
        $user62->provider_id = "4";
        $user62->week_id = "5";
        $user62->weekday_id = "6";
        $user62->day_start_time = "08:00:00";
        $user62->day_end_time = "17:00:00";
        $user62->off_day = "N";
        $user62->provider_schedule_type = "Monthly";
        $user62->created_by = "62";
        $user62->updated_by = "62";
        $user62->save();

        $user63 = new WeekDayAvailable;
        $user63->id = "63";
        $user63->provider_id = "4";
        $user63->week_id = "5";
        $user63->weekday_id = "7";
        $user63->day_start_time = "08:00:00";
        $user63->day_end_time = "17:00:00";
        $user63->off_day = "N";
        $user63->provider_schedule_type = "Monthly";
        $user63->created_by = "63";
        $user63->updated_by = "63";
        $user63->save();
    }
}
